gems: [jekyll-paginate]
paginate: 6
# sass:
#   style: compressed

title: Kiviok
author: kiviok
description: > # "url:"
  Тихое помешательство в рамках здравого смысла.
url: http://kiviok.ru

permalink: /:year/:month/:day/:title/
include: ["_pages", "js"]
exclude: ["node_modules", "gulpfile.js", "package.json"]


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
      canonical: true
