sass:
  style: compressed
title: Kiviok
permalink: pretty
author: kiviok
description: > # "url:"
 Сайт о хобби в программировании и веб-технологии.
url: http://kiviok.ru
kramdown:
  input: GFM
  syntax_highlighter: rouge
