gems: [jekyll-paginate]
paginate_path: /main/page:num
paginate: 5

sass:
  style: compressed

title: Kiviok
author: kiviok
description: > # "url:"
 Сайт о хобби в программировании и веб-технологии.
url: http://kiviok.ru

permalink: /:year/:month/:day/:title/
include: ["_pages"]
