sass:
  style: compressed
title: Kiviok
permalink: pretty
author: kiviok
description: > # "url:"
 Сайт с полезной информацией о фондовом рынке, опыте торговле на бирже,
 а также о хобби в программировании и веб-технологии.
url: http://kiviok.ru
